In [1]:
import pandas as pd

In [2]:
web_df1 = pd.read_csv("../data/raw/df_final_web_data_pt_1.txt")
web_df1

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04
...,...,...,...,...,...
343136,2443347,465784886_73090545671,136329900_10529659391_316129,confirm,2017-03-31 15:15:46
343137,2443347,465784886_73090545671,136329900_10529659391_316129,step_3,2017-03-31 15:14:53
343138,2443347,465784886_73090545671,136329900_10529659391_316129,step_2,2017-03-31 15:12:08
343139,2443347,465784886_73090545671,136329900_10529659391_316129,step_1,2017-03-31 15:11:37
343140,2443347,465784886_73090545671,136329900_10529659391_316129,start,2017-03-31 15:10:47

In [3]:
web_df2 = pd.read_csv("../data/raw/df_final_web_data_pt_2.txt")
web_df2

,client_id,visitor_id,visit_id,process_step,date_time
0,763412,601952081_10457207388,397475557_40440946728_419634,confirm,2017-06-06 08:56:00
1,6019349,442094451_91531546617,154620534_35331068705_522317,confirm,2017-06-01 11:59:27
2,6019349,442094451_91531546617,154620534_35331068705_522317,step_3,2017-06-01 11:58:48
3,6019349,442094451_91531546617,154620534_35331068705_522317,step_2,2017-06-01 11:58:08
4,6019349,442094451_91531546617,154620534_35331068705_522317,step_1,2017-06-01 11:57:58
...,...,...,...,...,...
412259,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:46:10
412260,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:45:29
412261,9668240,388766751_9038881013,922267647_3096648104_968866,step_1,2017-05-24 18:44:51
412262,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:44:34
412263,674799,947159805_81558194550,86152093_47511127657_716022,start,2017-06-03 12:17:09

## Data Cleaning

As we can see have two dataframes with the same name columns and they need to be cleaned. The first thing we need to do, since they are, basically,
the same dataframe split in two files is to merge them. From there, we will start the cleaning.

In [ ]:
df_web = pd.concat([web_df1, web_df2], axis=0)
df_web = df_web.reset_index(drop=True)
df_web.shape

(755405, 5)

In [6]:
#Check for nulls:
df_web.isnull().sum()

client_id       0
visitor_id      0
visit_id        0
process_step    0
date_time       0
dtype: int64

We are lucky! No nulls, but we can't celebrate yet, since even if it's filled, the data may be inconsistent

In [7]:
df_web.info()

<class 'pandas.DataFrame'>
RangeIndex: 755405 entries, 0 to 755404
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   client_id     755405 non-null  int64
 1   visitor_id    755405 non-null  str
 2   visit_id      755405 non-null  str
 3   process_step  755405 non-null  str
 4   date_time     755405 non-null  str
dtypes: int64(1), str(4)
memory usage: 28.8 MB

Client id should be an integer, correct, visitor and visit id should be strings as well as process step BUT date should be in date format

In [8]:
df_web['date_time'] = pd.to_datetime(df_web['date_time'])
df_web.info()

<class 'pandas.DataFrame'>
RangeIndex: 755405 entries, 0 to 755404
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   client_id     755405 non-null  int64
 1   visitor_id    755405 non-null  str
 2   visit_id      755405 non-null  str
 3   process_step  755405 non-null  str
 4   date_time     755405 non-null  datetime64[us]
dtypes: datetime64[us](1), int64(1), str(3)
memory usage: 28.8 MB

In [9]:
df_web.head()

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04

### Now, we need to keep in mind that our analysis will be to understand the behaviour of the customer. For that we need to sort it chronologically

In [10]:
df_web = df_web.sort_values(by=["client_id", "date_time"])
df_web.head(17)

,client_id,visitor_id,visit_id,process_step,date_time
285515,169,201385055_71273495308,749567106_99161211863_557568,start,2017-04-12 20:19:36
285514,169,201385055_71273495308,749567106_99161211863_557568,step_1,2017-04-12 20:19:45
285513,169,201385055_71273495308,749567106_99161211863_557568,step_2,2017-04-12 20:20:31
285512,169,201385055_71273495308,749567106_99161211863_557568,step_3,2017-04-12 20:22:05
285511,169,201385055_71273495308,749567106_99161211863_557568,confirm,2017-04-12 20:23:09
628456,336,64757908_3400128256,649044751_80905125055_554468,start,2017-06-01 07:26:55
628331,336,64757908_3400128256,649044751_80905125055_554468,start,2017-06-01 07:42:43
442857,546,475037402_89828530214,731811517_9330176838_94847,start,2017-06-17 10:03:29
442856,546,475037402_89828530214,731811517_9330176838_94847,step_1,2017-06-17 10:03:39
442855,546,475037402_89828530214,731811517_9330176838_94847,step_2,2017-06-17 10:03:52
442854,546,475037402_89828530214,731811517_9330176838_94847,step_3,2017-06-17 10:05:19
442853,546,475037402_89828530214,731811517_9330176838_94847,confirm,2017-06-17 10:05:42
72018,555,402506806_56087378777,637149525_38041617439_716659,start,2017-04-15 12:57:56
72017,555,402506806_56087378777,637149525_38041617439_716659,step_1,2017-04-15 12:58:03
72016,555,402506806_56087378777,637149525_38041617439_716659,step_2,2017-04-15 12:58:35
72015,555,402506806_56087378777,637149525_38041617439_716659,step_3,2017-04-15 13:00:14
72014,555,402506806_56087378777,637149525_38041617439_716659,confirm,2017-04-15 13:00:34

In [11]:
#save web file
df_web.to_csv('df_web.csv', index=False)

## Analyse the client behaviour in the conversion rate from start to confirm:

In [11]:
df_web.groupby("client_id")["process_step"].apply(list).head(20)

client_id
169              [start, step_1, step_2, step_3, confirm]
336                                        [start, start]
546              [start, step_1, step_2, step_3, confirm]
555              [start, step_1, step_2, step_3, confirm]
647              [start, step_1, step_2, step_3, confirm]
722     [start, step_1, step_2, step_1, start, step_1,...
786       [start, start, step_1, step_2, step_3, confirm]
805     [start, step_1, start, step_1, step_2, step_2,...
832     [start, step_1, step_2, step_1, step_2, step_3...
934                          [start, start, start, start]
1028    [start, step_1, step_1, step_2, step_3, step_1...
1039             [start, step_1, step_2, step_3, confirm]
1104                                       [start, start]
1186                       [start, start, step_1, step_2]
1195             [start, step_1, step_2, step_3, confirm]
1197    [start, step_1, step_2, step_3, step_2, step_3...
1281     [start, step_1, step_1, step_2, step_3, confirm]
1336    [start, step_1, step_2, step_3, confirm, confi...
1346    [start, step_1, start, step_1, step_2, step_3,...
1357             [start, step_1, step_2, step_3, confirm]
Name: process_step, dtype: object

### There are some irregularities, like starting many times, going upwards and backwards, confirming two times...

In [12]:
# Remove consecutive steps: 
df_web["prev_step"] = df_web.groupby("visit_id")["process_step"].shift()

df_web_clean = df_web[df_web["process_step"] != df_web["prev_step"]]

In [13]:
funnel_df = df_web_clean.pivot_table(
    index=["visit_id", "client_id"],
    columns="process_step",
    values="date_time",
    aggfunc="min"
)

In [14]:
funnel_df["converted"] = funnel_df["confirm"].notna()

### How many people reached the confirm step on average?:

In [15]:
conversion_rate = funnel_df["converted"].mean()
conversion_rate

np.float64(0.5695837236644389)

### 57% of the people, on average, reached the confirm step. These are the average on the diferent step process:

In [16]:
funnel_df.notna().mean()

process_step
confirm      0.569584
start        0.916600
step_1       0.755233
step_2       0.661069
step_3       0.602774
converted    1.000000
dtype: float64

### More than 8% of the population didn't start on start, which is the "normal" order. That might be because of uncomplete data or that somehow the process could be started in another step via direct access. Though, we think it's important to mention it to help developers

In [17]:
num_clients = df_web["client_id"].nunique()
print(f"Unique clients: {num_clients}.")

Unique clients: 120157.

## Completion Rate with a Cost-Effectiveness Threshold
Null Hypothesis ($H_0$): The completion rate for the Test group (new design) is equal to or less than the completion rate for the Control group (old design) increased by 5%.
Alternative Hypothesis ($H_a$): The completion rate for the Test group (new design) is greater than the completion rate for the Control group (old design) increased by 5%.
Note: a one-sided two-proportion z-test is appropriate.

Given the new threshold, you will compare the completion rate of the Test group to the completion rate of the Control group increased by 5%.

### 1) download the variation (test/control) table:

In [18]:
import yaml

In [19]:
with open("../config.yaml", "r") as file:
    config = yaml.safe_load(file)

In [20]:
expi_df = pd.read_csv(config["output_data"]["file2"])
expi_df

       client_id Variation
0        9988021      test
1        8320017      test
2        4033851   control
3        1982004      test
4        9294070   control
...          ...       ...
50495     393005   control
50496    2908510   control
50497    7230446      test
50498    5230357      test
50499    6334360      test

[50500 rows x 2 columns]

### 2) Merge it

In [21]:
joined_demo_expi_df = pd.merge(df_web_clean, expi_df, on= 'client_id')
display(joined_demo_expi_df)

,client_id,visitor_id,visit_id,process_step,date_time,prev_step,Variation
0,555,402506806_56087378777,637149525_38041617439_716659,start,2017-04-15 12:57:56,NaN,test
1,555,402506806_56087378777,637149525_38041617439_716659,step_1,2017-04-15 12:58:03,start,test
2,555,402506806_56087378777,637149525_38041617439_716659,step_2,2017-04-15 12:58:35,step_1,test
3,555,402506806_56087378777,637149525_38041617439_716659,step_3,2017-04-15 13:00:14,step_2,test
4,555,402506806_56087378777,637149525_38041617439_716659,confirm,2017-04-15 13:00:34,step_3,test
...,...,...,...,...,...,...,...
284552,9999729,834634258_21862004160,870243567_56915814033_814203,step_2,2017-05-08 16:08:40,step_1,test
284553,9999729,834634258_21862004160,870243567_56915814033_814203,step_3,2017-05-08 16:09:19,step_2,test
284554,9999729,834634258_21862004160,870243567_56915814033_814203,confirm,2017-05-08 16:09:40,step_3,test
284555,9999832,145538019_54444341400,472154369_16714624241_585315,start,2017-05-16 16:46:03,NaN,test
284556,9999832,145538019_54444341400,472154369_16714624241_585315,step_1,2017-05-16 16:46:11,start,test

### Now we got it ordered by client id and time. Both test and control (284557 rows)

In [27]:
df_Hipotesis = joined_demo_expi_df.sort_values(by=["client_id", "date_time",])
display(df_Hipotesis)

,client_id,visitor_id,visit_id,process_step,date_time,prev_step,Variation
0,555,402506806_56087378777,637149525_38041617439_716659,start,2017-04-15 12:57:56,NaN,test
1,555,402506806_56087378777,637149525_38041617439_716659,step_1,2017-04-15 12:58:03,start,test
2,555,402506806_56087378777,637149525_38041617439_716659,step_2,2017-04-15 12:58:35,step_1,test
3,555,402506806_56087378777,637149525_38041617439_716659,step_3,2017-04-15 13:00:14,step_2,test
4,555,402506806_56087378777,637149525_38041617439_716659,confirm,2017-04-15 13:00:34,step_3,test
...,...,...,...,...,...,...,...
284552,9999729,834634258_21862004160,870243567_56915814033_814203,step_2,2017-05-08 16:08:40,step_1,test
284553,9999729,834634258_21862004160,870243567_56915814033_814203,step_3,2017-05-08 16:09:19,step_2,test
284554,9999729,834634258_21862004160,870243567_56915814033_814203,confirm,2017-05-08 16:09:40,step_3,test
284555,9999832,145538019_54444341400,472154369_16714624241_585315,start,2017-05-16 16:46:03,NaN,test
284556,9999832,145538019_54444341400,472154369_16714624241_585315,step_1,2017-05-16 16:46:11,start,test

### We make a filter to have only the test (157680 rows)

In [28]:
df_test = df_Hipotesis[df_Hipotesis["Variation"] == "test"]
display(df_test)

,client_id,visitor_id,visit_id,process_step,date_time,prev_step,Variation
0,555,402506806_56087378777,637149525_38041617439_716659,start,2017-04-15 12:57:56,NaN,test
1,555,402506806_56087378777,637149525_38041617439_716659,step_1,2017-04-15 12:58:03,start,test
2,555,402506806_56087378777,637149525_38041617439_716659,step_2,2017-04-15 12:58:35,step_1,test
3,555,402506806_56087378777,637149525_38041617439_716659,step_3,2017-04-15 13:00:14,step_2,test
4,555,402506806_56087378777,637149525_38041617439_716659,confirm,2017-04-15 13:00:34,step_3,test
...,...,...,...,...,...,...,...
284552,9999729,834634258_21862004160,870243567_56915814033_814203,step_2,2017-05-08 16:08:40,step_1,test
284553,9999729,834634258_21862004160,870243567_56915814033_814203,step_3,2017-05-08 16:09:19,step_2,test
284554,9999729,834634258_21862004160,870243567_56915814033_814203,confirm,2017-05-08 16:09:40,step_3,test
284555,9999832,145538019_54444341400,472154369_16714624241_585315,start,2017-05-16 16:46:03,NaN,test
284556,9999832,145538019_54444341400,472154369_16714624241_585315,step_1,2017-05-16 16:46:11,start,test

### We make a filter to have only the control (126877 rows)

In [29]:
df_control = df_Hipotesis[df_Hipotesis["Variation"] == "control"]
display(df_control)

,client_id,visitor_id,visit_id,process_step,date_time,prev_step,Variation
11,1028,42237450_62128060588,557292053_87239438319_391157,start,2017-04-08 18:51:28,NaN,control
12,1028,42237450_62128060588,557292053_87239438319_391157,step_1,2017-04-08 18:52:17,start,control
13,1028,42237450_62128060588,557292053_87239438319_391157,step_2,2017-04-08 18:53:29,step_1,control
14,1028,42237450_62128060588,557292053_87239438319_391157,step_3,2017-04-08 18:58:04,step_2,control
15,1028,42237450_62128060588,557292053_87239438319_391157,step_1,2017-04-08 18:59:55,step_3,control
...,...,...,...,...,...,...,...
284509,9998346,292425655_16607136645,189177304_69869411700_783154,step_2,2017-03-29 15:30:11,step_1,control
284510,9998346,292425655_16607136645,189177304_69869411700_783154,step_3,2017-03-29 15:30:25,step_2,control
284511,9998346,292425655_16607136645,189177304_69869411700_783154,confirm,2017-03-29 15:37:28,step_3,control
284512,9998346,292425655_16607136645,189177304_69869411700_783154,step_3,2017-03-29 15:37:28,confirm,control
284523,9998921,960034051_85687824805,378424178_59565976155_8051,start,2017-04-18 11:26:31,NaN,control

### Next step is to get the completion rates for test and control. We start with test

In [30]:
completion_rate_test = df_test[df_test["process_step"] == "confirm"]["client_id"].nunique() / df_test["client_id"].nunique()

print(f"Completion rate test: {completion_rate_test:.2%}")

Completion rate test: 69.29%

### Now with Control:

In [31]:
completion_rate_control = df_control[df_control["process_step"] == "confirm"]["client_id"].nunique() / df_control["client_id"].nunique()

print(f"Completion rate control: {completion_rate_control:.2%}")

Completion rate control: 65.58%